# Generated by Django 4.2.2 on 2023-06-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201218_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.TextField(blank=True),
        ),
    ]
