# Generated by Django 4.2.2 on 2023-06-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_alias_id_alter_blogpost_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivMsg',
        ),
    ]
